#!/bin/sh
### BEGIN INIT INFO
# Provides:		roard
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	roard
### END INIT INFO
#
# Do not configure this file. Edit /etc/default/roard instead!
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/roard
NAME=roard
DESC="roard"

ROARD_EXTRA_ARGS=
NO_START=1

set -e

test ! -r /etc/default/roard || . /etc/default/roard
test "$NO_START" = "0" || exit 0
test -x "$DAEMON" || exit 0
test ! -h /var/service/roard || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: "
#	start-stop-daemon -S -x "$DAEMON" -- $ROARD_EXTRA_ARGS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON"
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
#	start-stop-daemon -K -x "$DAEMON"
	sleep 1
	start-stop-daemon -S -x "$DAEMON" -- $ROARD_EXTRA_ARGS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
