#! /bin/sh
#
# runvdr init.d script for Debian and compatible distributions
#
#      by Udo Richter <udo_richter(a)gmx.de>
#      http://www.richter-udo.de/vdr/scripts.html#runvdr
#

### BEGIN INIT INFO
# Provides:          runvdr-extreme
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: runvdr-extreme service
# Description:       Start the runvdr-extreme script that launches VDR
### END INIT INFO

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="runvdr-extreme"
NAME=runvdr-extreme
DAEMON=/usr/bin/runvdr-extreme
PIDFILE=/var/run/runvdr-extreme.pid
SCRIPTNAME=/etc/init.d/runvdr-extreme
CONFIG=/etc/runvdr/runvdr.conf

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

DEFAULT="/etc/default/runvdr-extreme"
if [ -f "$DEFAULT" ]; then  
	. "$DEFAULT" 
	if [ $ENABLED -lt 1 ]; then
		stop; exit 0
	fi
fi
	
#
#   Function that starts runvdr.
#
d_start() {
    start-stop-daemon --start --background --pidfile $PIDFILE \
        --exec $DAEMON -- -C $CONFIG
}

#
#   Function that stops runvdr.
#
d_stop() {
    $DAEMON --terminate=`cat $PIDFILE` --wait=30
}

#
#   Function that sends a restart to runvdr.
#
d_reload() {
    $DAEMON --restart=`cat $PIDFILE`
}

#
#   Function that sends a dvb-reload to runvdr.
#
d_dvb_reload() {
    $DAEMON --dvb-restart
}

case "$1" in
  start)
    echo -n "Starting $DESC: $NAME"
    d_start
    echo "."
    ;;
  stop)
    echo "Stopping $DESC: $NAME".
    d_stop
    ;;
  reload)
    echo -n "Reloading $DESC configuration"
    d_reload
    echo "."
  ;;
  dvb-reload|dvb-restart)
    echo -n "Reloading $DESC configuration"
    d_dvb_reload
    echo "."
  ;;
  restart|force-reload)
    echo -n "Restarting $DESC: $NAME"
    d_stop
    sleep 1
    d_start
    echo "."
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|dvb-restart|reload|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
